### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by divyang-mittal**
Add restart screen to the game also a template function to easily enter
 text in our functions. Had to set up clock and fps for it.

### CODE REVIEW

**Comment by vineetjc** [comment]
@divyang-mittal conflicts must be resolved, make sure you're on the latest version of the repo

**Comment by divyang-mittal** [comment]
I am not on the latest version can you help me on how to get to it

**Comment by divyang-mittal** [comment]
I have updated my repo so review this one

**Comment by divyang-mittal** [comment]
I am going to make a new pull request with updated repo

**Pull request closed without merging**
