### PR TITLE
Corrected overlapping KEY IMAGE

### PR DESCRIPTION
**Pull request by piba941**

### CODE REVIEW

**Comment by vineetjc** [comment]
@piba941 please update your repo and send this PR again

**Comment by vineetjc** [comment]
@piba941 the key is now overlapping the bottom of the grid, so you could either do one of the following:

- Remove that key picture from displaying
- Remove the thermometer picture in the last frame and show the key picture
- make a new frame

**Comment by piba941** [comment]
I have removed the overlapping KEY IMAGE as asked !

**Comment by vineetjc** [comment]
@piba941 update your main.py, it's changed from before with a start screen and how to

**Comment by vineetjc** [comment]
@piba941 I sent you a pull request with the latest changes, please 'git pull' always from my repo before working

**Comment by vineetjc** [comment]
Merging it @piba941 , apologies from my end, good work on fixing the bug, but keep updating your repo alright? Good work again!

**Pull request merged**
